# Generated by Django 4.2.5 on 2023-10-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favorite_film_genre',
            field=models.CharField(choices=[('Select Genre', 'Select Genre'), ('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Romance', 'Romance'), ('Science Fiction', 'Science Fiction'), ('Horror', 'Horror')], default='Select Genre', max_length=100),
        ),
    ]
