# Generated by Django 4.2.5 on 2023-10-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='personal_rating',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
