# Generated by Django 4.2.6 on 2023-10-25 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ranking.comment'),
        ),
    ]
