# Generated by Django 4.2.6 on 2023-10-26 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0005_ranking_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
