# Generated by Django 4.2.6 on 2023-10-31 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0006_remove_comment_movie_remove_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='comment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ranking.comment'),
        ),
    ]
